---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: garden
    release: garden-runc
  - name: csi-nfs-plugin
    release: csi-plugin
    properties:
      csi-nfs-plugin:
        mount_root_path: /var/vcap/store
        start_command: "nfsplugin --endpoint tcp://127.0.0.1:10000 --nodeid CSINode -v=5"
  name: csi-test
  networks:
  - name: default
  stemcell: default
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: small-highmem

name: csi-test
releases:
- name: garden-runc
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.11.1
  version: 1.11.1
- name: csi-plugin
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3468.22'

update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: 1
  serial: false
  update_watch_time: 5000-1200000
variables: []
